---
#Main config file for sql-role

- name: Check if sysctl executable exists. If not, swappiness cannot be set!
  stat:
    path: /usr/sbin/sysctl
  register: sysctl_check

- name: Configure swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ mariadb_swappiness }}"
    state: present
  when:
    - mariadb_configure_swappiness|bool
    - sysctl_check.stat.exists
  tags: mariadb

# SELinux context mysqld_log_t is default for /var/log/mariadb
- name: Create log directory
  file:
    state: directory
    path: /var/log/mariadb
    owner: mysql
    group: mysql
    mode: 0755
  when: mariadb_logrotate.configure|bool

- name: Configure logrotate
  template:
    src: etc_logrotate.d_mysql.j2
    dest: /etc/logrotate.d/mysql
    mode: 0644
  when: mariadb_logrotate.configure|bool
  notify: restart mariadb
  tags: mariadb

- name: Ensure service is started
  service:
    name: "{{ mariadb_service }}"
    state: started
    enabled: true
  tags: mariadb
