---

- name: enable firewalld
  service:
    name: firewalld
    enabled: yes
  tags: apache

- name: Start and enable Apache
  service:
    name:  httpd
    state: started
    enabled: yes
  tags: apache

