---
#Firewalld config
- name: Install firewalld
  yum:
    name: firewalld
    state: present
  tags: apache 

- name: Start firewalld
  service:
    name:  firewalld
    state: started
  tags: apache

- name: Config firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - 22/tcp
    - 80/tcp
  tags: apache

- name: Reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
  notify:
  - enable firewalld
  tags: apache



    
 
  
